source 'https://rubygems.org'

gem 'rails', '~> 5.0.0'
gem 'mysql2'

gem 'rmagick'
gem 'mini_magick'
gem 'carrierwave'

gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'bootstrap-sass'
gem 'font-awesome-rails'
gem 'lodash-rails'

gem 'dotenv-rails'
gem 'uuidtools'
gem 'rabl'

group :development do
  gem 'listen'
  gem 'capistrano'
  gem 'capistrano-rails'
  gem 'capistrano-rbenv'
  gem 'capistrano-bundler'
  gem 'capistrano-passenger', '0.0.2'
end

group :production do
  gem 'therubyracer'
  gem 'libv8'
end
